# -*- coding: utf-8 -*-
"""StudentPerformance

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Swyg29jZH7kuQUt3EcjgnH3tdol7OqY
"""

import pandas as pd
import numpy as np
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=pd.errors.SettingWithCopyWarning)

data =  pd.read_csv('StudentPerformanceFactors.csv')

data.head()

data.info()

data.describe()

# número de valores nulos
data.isnull().sum()

#Preenchendo valores nulos
data.Teacher_Quality.fillna(data['Teacher_Quality'].mode()[0], inplace=True )
data.Parental_Education_Level.fillna(data['Parental_Education_Level'].mode()[0], inplace=True )
data.Distance_from_Home.fillna(data['Distance_from_Home'].mode()[0], inplace=True )

data.Physical_Activity.unique()

numerical_data = data.select_dtypes(include=['int64', 'float64'])


corr_matrix = numerical_data.corr()


plt.figure(figsize=(10, 6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title("Correlation Matrix of Numerical Features")
plt.show()

px.histogram(data ,
            x = 'Exam_Score',
            title = 'Pontuação do Exame')

fig = px.histogram(data, x='Hours_Studied', nbins=20, title='Horas Estudadas')
fig.show()

fig = px.bar(data ,
             x = 'Gender',
            title="Gráfico de Gênero")
fig.show()